fix parsing of historical vote legislator lookup to not mind if a legislator has two terms on Jan 3
After recent updates to congress-legislator historical start/end dates, we began getting:

Multiple matches of name Slaughter (VA-R; 1991-01-03) to legislators (excludes set([])).
[h1-102.1991] Missing bioguide ID and name lookup failed for Slaughter (VA-R on 1991-01-03 12:02:00)
Exception: No bioguide ID for Slaughter (VA-R)

But there weren't really multiple legislators matching, just multiple terms.

(There are other new cases of multiple legislators matching now though too.)