I broke parsing hres1-104 because of "House House Oversight"
In db1d414e47583ece35d3c5bd3b43074d8eeaf66d I added a fix for parsing "House Oversight" in the
105th Congress, but this broke a different way of handling the same problem for the 104th
Congress which I had previously done in c70396dbd39d196a87e8984d064e703d7fc595c6.

Not sure how this just broke one bill, but here it is:

[hres1-104] Exception:

Traceback (most recent call last):

  File "tasks/utils.py", line 144, in process_set
    results = fetch_func(id, options, *extra_args)

  File "tasks/bill_info.py", line 27, in fetch_bill
    if not utils.committee_names: utils.fetch_committee_names(congress, options)

  File "tasks/utils.py", line 559, in fetch_committee_names
    committee_names["House Oversight"] = committee_names["House House Oversight"]

KeyError: 'House House Oversight'